version: "3"

services:
  # server:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     SEED: "true"
  #     ENV: "production"
  #     PORT: 8000
  #     INFLUXDB_ENDPOINT: http://influxdb:8086/
  #   links:
  #     - influxdb:influxdb
  #   depends_on:
  #     - influxdb
  #   restart: unless-stopped
  influxdb:
    image: influxdb:1.7-alpine
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
    environment:
      INFLUXDB_ADMIN_ENABLED: "true"
      INFLUXDB_DB: "sleep_well"
    volumes:
      - ./data:/var/lib/influxdb
    restart: unless-stopped
